config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :bows, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :orders, only: [:create, :show, :index] do
    resources :payments, only: [:new, :create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bow.rb
class Bow < ApplicationRecord
  has_many :orders
  has_many :reviews
  has_many :users, through: :orders
  monetize :price_cents

  validates :size, presence: true
  validates :color, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :bow
  belongs_to :user
  monetize :amount_cents
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :bow
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
has_many :reviews, dependent: :destroy
has_many :orders, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  # validates :last_name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bows_controller.rb
class BowsController < ApplicationController
skip_before_action :authenticate_user!, only: :index
before_action :set_bow, only: [:show, :edit, :update, :destroy]

  def index
    @bows = policy_scope(Bow)
  end

  def new
    @bow = Bow.new
    authorize @bow
  end


   def create
    @bow = Bow.new(bow_params)
    @bow.user = current_user
    authorize @bow

    if @bow.save
      redirect_to bows_path
    else
      render "new"
    end
  end

  def show
    authorize @bow
  end

  def edit

  end

  def update
   if @bow.update(bow_params)
      redirect_to bows_path
    else
      render :edit
    end
    authorize @bow
  end

  def destroy
    if @bow.delete
      redirect_to bows_path
    end
  end

  private

    def set_bow
      @bow = Bow.find(params[:id])
      authorize @bow
    end

    def bow_params
      params.require(:bow).permit("color", "size", "description", "photo", "num_in_stock", "price_cents")
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @bows = policy_scope(Bow)
  end

  def create
    bow = Bow.find(params[:bow_id])
    order = Order.create!(bow_sku: bow.sku, state: "pending", amount: bow.price, user: current_user, bow: bow)
    authorize order
    redirect_to new_order_payment_path(order)
  end

  def show
    @order = current_user.orders.find(params[:id])
    authorize @order
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order

  def new

  end

  def create

    # customer = Stripe::Customer.create(
    # source: params[:stripeToken],
    # email:  params[:stripeEmail]
    # )

    # charge = Stripe::Charge.create(
    #   customer:     customer.id,   # You should store this customer id and re-use it.
    #   amount:       @order.amount_cents,
    #   description:  "Payment for bow #{@order.bow_sku} for order #{@order.id}",
    #   currency:     @order.amount.currency
    # )

    # @order.update(payment: charge.to_json, state: 'paid')
    # redirect_to order_path(@order)

    # rescue Stripe::CardError => e
    #   flash[:alert] = e.message
    #   redirect_to new_order_payment_path(@order)
  end

  private

    def set_order
      @order = current_user.orders.where(state: 'pending').find(params[:order_id])
      authorize @order
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bows/_new_bow_form.html.erb
<div class="form container">
  <div class="row">
    <div class="col-xs-offset-2 col-xs-8 form-column">

      <%= simple_form_for(@bow) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        <%= f.input :description, required: false, label: "description of bow", prompt: "description" %>
        <%= f.input :color, required: false %>
        <%= f.input :size, required: false %>
        <%= f.input :photo, required: false %>
        <%= f.input :price_cents, required: false %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, :class => "create-button" %>
      </div>
      <%= link_to 'Back', bows_path%>
      <% end %>
    </div>
  </div>
</div>

app/views/bows/edit.html.erb
<h1> Edit your bow </h1>

<%= render 'new_bow_form' %>

<%= link_to 'Back', bows_path %>

app/views/bows/index.html.erb
<div class="wrapper">

  <div class="sort">

  </div>

  <div class="container">
    <div class="row">
     <!--  <div class="col-xs-4 col-xs-offset-0"> -->
        <div class="cards">
          <% @bows.each do |bow|%>
            <%= link_to bow_path(bow) do %>
              <div class="bow-card">
                <div class="card-photo">
                <!-- link to photo url -->
                </div>
                <div class="card-description">
                  <%= bow.description %>
                  <p>Price: <%= humanized_money_with_symbol(bow.price) %></p>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <%= link_to "Add a new bow", new_bow_path %>

</div>

app/views/bows/new.html.erb
 <%= render 'new_bow_form' %>

app/views/bows/show.html.erb
<!-- need to review - do we want this to be an admin feature? -->
<%#= link_to "edit bows", edit_bow_path if current_user == @bow.user %>


<%# if current_user == @bow.user %>
<%#=  link_to "Delete", bow_path(@bow),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
  <%# end %>

<div class="wrap">
  <div class="bow-photo">
    <!-- put in photo here -->
  </div>


  <div class="purchase">
    <%= form_tag orders_path do %>
    <%= hidden_field_tag 'bow_id', @bow.id %>
    <%= submit_tag 'Purchase', class: 'btn btn-primary' %>
  <% end %>
  </div>

  <%= link_to "back to bows", bows_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/orders/index.html.erb
<p> test </p>
<% if policy(Order).index? %>
  <%= link_to "Order", orders_path %>
<% end %>

app/views/orders/show.html.erb
<h1>Order</h1>
<ul>
  <li>Status: <%= @order.state %></li>
  <li>Item: <%= @order.bow_sku %></li>
  <li>Amount: <%= humanized_money_with_symbol(@order.amount) %></li>
<ul>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>Braintree Bows</h1>
     <div class="link">
       <%= link_to 'Shop for bows here', bows_path  %>
     </div>
  </div>
</div>

app/views/payments/new.html.erb
<h1>Purchase of bow <%= @order.bow_sku %></h1>
<%= form_tag order_payments_path(@order) do %>
  <article>
    <label class="amount">
      <span>Amount: <%= humanized_money_with_symbol(@order.amount) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="My Bow"
    data-email="<%= current_user.email %>"
    data-description="Bow <%= @order.bow_sku %>"
    data-amount="<%= @order.amount_cents %>"
    data-currency="<%= @order.amount.currency %>"></script>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="nav-home">
  <div><h4><%= link_to "BraintreeBows", root_path, id:"logo" %></h4></div>
  <ul>
    <li>
      <%= link_to "Bows", bows_path  %>
    </li>
    <li>
      <%= link_to "Orders", orders_path %>
    </li>
    <li>
      <% if user_signed_in? %>
        <%= link_to destroy_user_session_path, method: :delete do %>
        <%= t(".sign_out", default: "Logout") %>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path do  %>
        <%= t(".sign_in", default: "Login") %>
        <% end %>
      <% end %>
    </li>
  </ul>
</nav>